import Header from '@/layouts/header/header'
import Footer from '@/layouts/footer/footer'
import '@/styles/app.scss'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   manifest: '/manifest.json',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}