import Header from '@/layouts/header/header'
import localFont from 'next/font/local'
import Footer from '@/layouts/footer/footer'
import '@/styles/app.scss'

const gilroy = localFont({
  src: [
    {
      path: '../public/fonts/gilroy-light-webfont.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/gilroy-regular-webfont.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/gilroy-semibold-webfont.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/gilroy-bold-webfont.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/gilroy-extrabold-webfont.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   manifest: '/manifest.json',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={gilroy.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}